resource_group_name = "packer-rsg"
storage_account     = "packerstg01"
location            = "eastus"
client_id           = ""
subscription_id     = ""
tenant_id           = ""
client_secret       = ""
